name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  http: ^1.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  gallery_saver:
    path: ../

flutter:
  uses-material-design: true
